// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/aescbc.dart';
import 'api/conwork.dart';
import 'api/jwxt/course.dart';
import 'api/jwxt/dekt.dart';
import 'api/jwxt/elective.dart';
import 'api/jwxt/exam.dart';
import 'api/jwxt/info.dart';
import 'api/jwxt/plan.dart';
import 'api/jwxt/score.dart';
import 'api/jwxt/semester.dart';
import 'api/session.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcCookieStoreMutexPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcCookieStoreMutex;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ClientPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CryptoErrorPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_HttpSessionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession;

  @protected
  ArcCookieStoreMutex
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcCookieStoreMutex(
    dynamic raw,
  );

  @protected
  Client
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    dynamic raw,
  );

  @protected
  CryptoError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    dynamic raw,
  );

  @protected
  HttpSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    dynamic raw,
  );

  @protected
  HttpSession
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    dynamic raw,
  );

  @protected
  HttpSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    dynamic raw,
  );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  ArcCookieStoreMutex
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcCookieStoreMutex(
    dynamic raw,
  );

  @protected
  Client
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    dynamic raw,
  );

  @protected
  CryptoError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    dynamic raw,
  );

  @protected
  HttpSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CourseSchedule dco_decode_course_schedule(dynamic raw);

  @protected
  CreditInfo dco_decode_credit_info(dynamic raw);

  @protected
  DEKT dco_decode_dekt(dynamic raw);

  @protected
  DEKTDetail dco_decode_dekt_detail(dynamic raw);

  @protected
  DEKTList dco_decode_dekt_list(dynamic raw);

  @protected
  DEKTTotal dco_decode_dekt_total(dynamic raw);

  @protected
  ElectiveResponse dco_decode_elective_response(dynamic raw);

  @protected
  ExamSchedule dco_decode_exam_schedule(dynamic raw);

  @protected
  ExecutionPlan dco_decode_execution_plan(dynamic raw);

  @protected
  ExecutionPlanResponse dco_decode_execution_plan_response(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CourseSchedule> dco_decode_list_course_schedule(dynamic raw);

  @protected
  List<CreditInfo> dco_decode_list_credit_info(dynamic raw);

  @protected
  List<DEKTList> dco_decode_list_dekt_list(dynamic raw);

  @protected
  List<DEKTTotal> dco_decode_list_dekt_total(dynamic raw);

  @protected
  List<ExamSchedule> dco_decode_list_exam_schedule(dynamic raw);

  @protected
  List<ExecutionPlan> dco_decode_list_execution_plan(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<ScoreInfo> dco_decode_list_score_info(dynamic raw);

  @protected
  List<SemesterInfo> dco_decode_list_semester_info(dynamic raw);

  @protected
  List<XqxkchInfo> dco_decode_list_xqxkch_info(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  ScoreInfo dco_decode_score_info(dynamic raw);

  @protected
  ScoreSummary dco_decode_score_summary(dynamic raw);

  @protected
  ScoreTotal dco_decode_score_total(dynamic raw);

  @protected
  SemesterInfo dco_decode_semester_info(dynamic raw);

  @protected
  StudentInfo dco_decode_student_info(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  XqxkchInfo dco_decode_xqxkch_info(dynamic raw);

  @protected
  ArcCookieStoreMutex
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcCookieStoreMutex(
    SseDeserializer deserializer,
  );

  @protected
  Client
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    SseDeserializer deserializer,
  );

  @protected
  CryptoError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    SseDeserializer deserializer,
  );

  @protected
  HttpSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    SseDeserializer deserializer,
  );

  @protected
  HttpSession
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    SseDeserializer deserializer,
  );

  @protected
  HttpSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  ArcCookieStoreMutex
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcCookieStoreMutex(
    SseDeserializer deserializer,
  );

  @protected
  Client
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    SseDeserializer deserializer,
  );

  @protected
  CryptoError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    SseDeserializer deserializer,
  );

  @protected
  HttpSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CourseSchedule sse_decode_course_schedule(SseDeserializer deserializer);

  @protected
  CreditInfo sse_decode_credit_info(SseDeserializer deserializer);

  @protected
  DEKT sse_decode_dekt(SseDeserializer deserializer);

  @protected
  DEKTDetail sse_decode_dekt_detail(SseDeserializer deserializer);

  @protected
  DEKTList sse_decode_dekt_list(SseDeserializer deserializer);

  @protected
  DEKTTotal sse_decode_dekt_total(SseDeserializer deserializer);

  @protected
  ElectiveResponse sse_decode_elective_response(SseDeserializer deserializer);

  @protected
  ExamSchedule sse_decode_exam_schedule(SseDeserializer deserializer);

  @protected
  ExecutionPlan sse_decode_execution_plan(SseDeserializer deserializer);

  @protected
  ExecutionPlanResponse sse_decode_execution_plan_response(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CourseSchedule> sse_decode_list_course_schedule(
    SseDeserializer deserializer,
  );

  @protected
  List<CreditInfo> sse_decode_list_credit_info(SseDeserializer deserializer);

  @protected
  List<DEKTList> sse_decode_list_dekt_list(SseDeserializer deserializer);

  @protected
  List<DEKTTotal> sse_decode_list_dekt_total(SseDeserializer deserializer);

  @protected
  List<ExamSchedule> sse_decode_list_exam_schedule(
    SseDeserializer deserializer,
  );

  @protected
  List<ExecutionPlan> sse_decode_list_execution_plan(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<ScoreInfo> sse_decode_list_score_info(SseDeserializer deserializer);

  @protected
  List<SemesterInfo> sse_decode_list_semester_info(
    SseDeserializer deserializer,
  );

  @protected
  List<XqxkchInfo> sse_decode_list_xqxkch_info(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  ScoreInfo sse_decode_score_info(SseDeserializer deserializer);

  @protected
  ScoreSummary sse_decode_score_summary(SseDeserializer deserializer);

  @protected
  ScoreTotal sse_decode_score_total(SseDeserializer deserializer);

  @protected
  SemesterInfo sse_decode_semester_info(SseDeserializer deserializer);

  @protected
  StudentInfo sse_decode_student_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  XqxkchInfo sse_decode_xqxkch_info(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcCookieStoreMutex(
    ArcCookieStoreMutex self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    Client self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    CryptoError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    HttpSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    HttpSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    HttpSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcCookieStoreMutex(
    ArcCookieStoreMutex self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    Client self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    CryptoError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    HttpSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_course_schedule(
    CourseSchedule self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_credit_info(CreditInfo self, SseSerializer serializer);

  @protected
  void sse_encode_dekt(DEKT self, SseSerializer serializer);

  @protected
  void sse_encode_dekt_detail(DEKTDetail self, SseSerializer serializer);

  @protected
  void sse_encode_dekt_list(DEKTList self, SseSerializer serializer);

  @protected
  void sse_encode_dekt_total(DEKTTotal self, SseSerializer serializer);

  @protected
  void sse_encode_elective_response(
    ElectiveResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_exam_schedule(ExamSchedule self, SseSerializer serializer);

  @protected
  void sse_encode_execution_plan(ExecutionPlan self, SseSerializer serializer);

  @protected
  void sse_encode_execution_plan_response(
    ExecutionPlanResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_course_schedule(
    List<CourseSchedule> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_credit_info(
    List<CreditInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dekt_list(List<DEKTList> self, SseSerializer serializer);

  @protected
  void sse_encode_list_dekt_total(
    List<DEKTTotal> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_exam_schedule(
    List<ExamSchedule> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_execution_plan(
    List<ExecutionPlan> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_score_info(
    List<ScoreInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_semester_info(
    List<SemesterInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_xqxkch_info(
    List<XqxkchInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_score_info(ScoreInfo self, SseSerializer serializer);

  @protected
  void sse_encode_score_summary(ScoreSummary self, SseSerializer serializer);

  @protected
  void sse_encode_score_total(ScoreTotal self, SseSerializer serializer);

  @protected
  void sse_encode_semester_info(SemesterInfo self, SseSerializer serializer);

  @protected
  void sse_encode_student_info(StudentInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_xqxkch_info(XqxkchInfo self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcCookieStoreMutex(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcCookieStoreMutex(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcCookieStoreMutex(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcCookieStoreMutex(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcCookieStoreMutex(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcCookieStoreMutex(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCryptoError(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpSession(
    int ptr,
  );
}
