// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

Future<List<ExamSchedule>> parseExam({required String html}) =>
    RustLib.instance.api.crateApiJwxtExamParseExam(html: html);

class ExamSchedule {
  final int id;
  final String courseCode;
  final String courseName;
  final String examTime;
  final String examLocation;

  const ExamSchedule({
    required this.id,
    required this.courseCode,
    required this.courseName,
    required this.examTime,
    required this.examLocation,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      courseCode.hashCode ^
      courseName.hashCode ^
      examTime.hashCode ^
      examLocation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExamSchedule &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          courseCode == other.courseCode &&
          courseName == other.courseName &&
          examTime == other.examTime &&
          examLocation == other.examLocation;
}
