// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

Future<StudentInfo> parseStudentInfo({required String html}) =>
    RustLib.instance.api.crateApiJwxtInfoParseStudentInfo(html: html);

class StudentInfo {
  final String name;
  final String gender;
  final String studentId;
  final String department;
  final String major;
  final String className;
  final String admissionDate;
  final String admissionNumber;
  final String idNumber;

  const StudentInfo({
    required this.name,
    required this.gender,
    required this.studentId,
    required this.department,
    required this.major,
    required this.className,
    required this.admissionDate,
    required this.admissionNumber,
    required this.idNumber,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      gender.hashCode ^
      studentId.hashCode ^
      department.hashCode ^
      major.hashCode ^
      className.hashCode ^
      admissionDate.hashCode ^
      admissionNumber.hashCode ^
      idNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StudentInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          gender == other.gender &&
          studentId == other.studentId &&
          department == other.department &&
          major == other.major &&
          className == other.className &&
          admissionDate == other.admissionDate &&
          admissionNumber == other.admissionNumber &&
          idNumber == other.idNumber;
}
