// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<SemesterInfo>> parseSemester({
  required String html,
  required bool isAll,
}) => RustLib.instance.api.crateApiJwxtSemesterParseSemester(
  html: html,
  isAll: isAll,
);

class SemesterInfo {
  final String key;
  final String value;

  const SemesterInfo({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SemesterInfo &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}
