// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`, `from`, `source`

/// AES-128 CBC encryption with PKCS7 padding, output base64 string
Future<String> aesCbcEncrypt({required String plainText}) =>
    RustLib.instance.api.crateApiAescbcAesCbcEncrypt(plainText: plainText);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CryptoError>>
abstract class CryptoError implements RustOpaqueInterface {}
