// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `login_jwxt`, `login_vpn`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < CookieStoreMutex >>>
abstract class ArcCookieStoreMutex implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Client>>
abstract class Client implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HttpSession>>
abstract class HttpSession implements RustOpaqueInterface {
  Future<bool> accessJwxt();

  ArcCookieStoreMutex get cookieStore;

  Client get client;

  set cookieStore(ArcCookieStoreMutex cookieStore);

  set client(Client client);

  Future<String> completeLogin({
    required String username,
    required String vpnPassword,
    required String oaPassword,
  });

  Future<String> getFlowExecutionKey();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<HttpSession> newInstance() =>
      RustLib.instance.api.crateApiSessionHttpSessionNew();
}
