// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'jwxt/course.dart';
import 'jwxt/dekt.dart';
import 'jwxt/elective.dart';
import 'jwxt/exam.dart';
import 'jwxt/info.dart';
import 'jwxt/plan.dart';
import 'jwxt/score.dart';
import 'jwxt/semester.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> apiLogin({
  required String username,
  required String vpnPassword,
  required String oaPassword,
}) => RustLib.instance.api.crateApiSimpleApiLogin(
  username: username,
  vpnPassword: vpnPassword,
  oaPassword: oaPassword,
);

Future<StudentInfo> apiStudentInfo() =>
    RustLib.instance.api.crateApiSimpleApiStudentInfo();

Future<List<SemesterInfo>> apiSemester({required bool isAll}) =>
    RustLib.instance.api.crateApiSimpleApiSemester(isAll: isAll);

Future<ScoreTotal> apiScore({required String semester}) =>
    RustLib.instance.api.crateApiSimpleApiScore(semester: semester);

Future<List<CourseSchedule>> apiCourse({required String semester}) =>
    RustLib.instance.api.crateApiSimpleApiCourse(semester: semester);

Future<List<ExamSchedule>> apiExam({required String semester}) =>
    RustLib.instance.api.crateApiSimpleApiExam(semester: semester);

Future<ElectiveResponse> apiElective({required String semester}) =>
    RustLib.instance.api.crateApiSimpleApiElective(semester: semester);

Future<ExecutionPlanResponse> apiPlan() =>
    RustLib.instance.api.crateApiSimpleApiPlan();

Future<DEKT> apiDekt() => RustLib.instance.api.crateApiSimpleApiDekt();

Future<DEKTDetail> apiDektDetail({required String id}) =>
    RustLib.instance.api.crateApiSimpleApiDektDetail(id: id);
